README.md

Hi,
This looks like a great project, I will definitely try it when I get the chance!
I've read the Readme and changed a few things.
You might want to consider organizing some of the explanations and tutorials in a Wiki section, or maybe create a starter "Hello world" project. This will help shorten the Readme, and make this project less imposing for newcomers like me.

Readme spell-checking

---

src/PSR7Client.php

#67 
Normalizing protocol version strings to match official values 1.0, 1.1 and 2

#67 Unsupported HTTP protocol version "2.0"

---

service/http/request.go

Fix unknown methods content stream (json on body in custom method set)

---

.rr.yaml
composer.json
src/bin/roadrunner

Resolves #71 
I tried to create CLI. Waiting for your comments and suggestions.
Tested on MacOS. Works fine.

RoadRunner CLI for binary update and config initialization

---

composer.json

Fixes merge issue from e303434db0930339bb7aa89b904848e92483703f

Fixed `composer.json` merge issue (#155)

---

cmd/rr/cmd/serve.go

Feature(rr): Serve - dont ignore error from container.Serve

---

.rr.yaml
go.mod
service/http/config.go
service/http/config_test.go
service/http/fcgi_test.go
service/http/service.go
service/http/service_test.go
service/rpc/config.go
service/rpc/config_test.go
util/network.go
util/network_test.go

Feature - FastCGI support for HTTP Service

---

.rr.yaml
service/http/config.go
service/http/config_test.go
service/http/service.go

Service(http): Support configuration for HTTP2 (and disabling)

---

.rr.yaml
service/http/config.go
service/http/service.go

Hey!
Example (my configuration):
```yaml
middlewares:
cors:
allowedOrigins: "*"
allowedHeaders: "*"
allowedMethods: "GET,POST,PUT,DELETE"
maxAge: 600
headers:
customResponseHeaders:
"X-Powered-By": "Sega 16 bit"
```
Thanks

Middlewares headers

---

service/http/service.go

@wolfy-j I tried to implement #172 
Honestly, I don't know ho to test it...
Maybe @filakhtov can help?

Attempt to add h2c handling (http2 w/o ssl)

---

Makefile

Looks like "build" and "all" commands are mixed up.

Switch "make build" and "make all" commands

---

bin/rr
cmd/rr/cmd/root.go

- add ability  get-binary command to skip the same version downloading

---

service/http/config.go
service/http/config_test.go
service/http/handler.go
service/http/handler_test.go

Bug fix/183 wrong proxy resolving

---

service/http/request.go

Hi there,
as you know `HTTP` handle body content on `GET` requests, and also `Laravel` support it.
we can allow GET requests to support body contents.

handle body content on http GET method

---

.github/workflows/blank.yml
.github/workflows/ci-build.yml

- Add ci file for supporting Github Actions
Sometimes test failed with error such as [here](https://travis-ci.org/spiral/roadrunner/jobs/601350886?utm_medium=notification&utm_source=github_status)
Link on success ci jobs you can see [here](https://github.com/Smolevich/roadrunner/commit/14dac9be74e95185a3bf6c724559de5349a1a6e0/checks?check_suite_id=278333602)

Add support for GitHub actions

---

composer.json

Add support of symfony/console version 5

#211 Support Symfony 5

---

server_config.go
service/container.go
service/container_test.go
service/http/service.go
service/metrics/rpc_test.go
service/metrics/service.go

- the ability to set custom command producer for roadrunner
- minor improvements in metrics service
- List() function for Container to receive names of all available services

[wip] Hot-reloading capabilities - review wanted

---

.github/workflows/ci-build.yml
.travis.yml
composer.json
phpstan.neon.dist
src/Diactoros/StreamFactory.php
src/Diactoros/UploadedFileFactory.php
src/HttpClient.php
src/Metrics.php
src/MetricsInterface.php
src/PSR7Client.php
src/Worker.php

This PR contains:
- Updated GitHub Actions workflow (added composer depenndencies cache, large steps decomposed, added static code analyzer running)
- Updated travis config (added static code analyzer running)
- Updated `composer.json` (`phpstan/phpstan` added as `dev` dependency, also added `analyze` "script" for phpstan running)
- File `phpstan.neon.dist` with phpstan config
- A little bit updated PHP sources (for passing **max** phpstan level analyze)

Optimize GitHub Actions workflow and integrate static code analyzer (phpstan)

---

service/http/fcgi_test.go
service/http/request.go
tests/http/request-uri.php

For https://github.com/spiral/roadrunner/issues/232 issue

fix REQUEST_URI for requests through FastCGI

---

service/gzip/service_test.go

Here was a bug which prevented to run application. Unused import.

Fix bug with unused import

---

service/static/service_test.go

Rotate ports

---

service/static/service_test.go

Remove defers (go ..., then defer)
Resolves #220

Fix for failing tests

---

composer.json

https://github.com/spiral/roadrunner/blob/a208e27c9d8f4558328c3931c960f155a02e786f/bin/rr#L41-L44

Explicitly require Curl since bin/rr doesn't work without it

---

CHANGELOG.md
build.sh

@wolfy-j BORS is ready to help you :)

Prepare to 1.6.3 release

---

CHANGELOG.md
go.mod

prepare_to_1_6_3

---

go.mod
go.sum
service/container.go
service/container_test.go
service/gzip/service.go
service/gzip/service_test.go

Fix panic and RR freeze on empty config
Uncomment test for container. It's working properly now
Fix potential issue in gzip with cfg initialization
resolves #276

Fix panic and stuck

---

build.sh

Add -trimpath to the build script

---

.dockerignore
.github/workflows/ci-build.yml
.gitignore
Makefile
bors.toml
composer.json
service/headers/service_test.go
tests/client.php
tests/http/client.php
tests/http/slow-client.php
tests/slow-client.php
tests/slow-destroy.php

Vendor directory fix (php vs golang)

---

service/limit/service_test.go
systemd/rr.service

rr.service unit file

---

server_config_test.go
service/http/rpc_test.go
service/rpc/config_test.go
socket_factory_test.go

remove windows check from sockets tests

---

composer.json
src/Worker.php

Reduce syscalls usage

---

src/Worker.php

Add non-optimized relays support

---

service/http/handler.go

Hi guys,
this PR will add support of CF-Connecting-IP and True-Client-IP headers, that provided by cloudflare, in some cases it may be very useful - https://support.cloudflare.com/hc/en-us/articles/206776727-What-is-True-Client-IP-

Add support of CloudFlare CF-Connecting-IP and True-Client-IP headers

---

CHANGELOG.md
Dockerfile
build.sh
cmd/rr/main.go
service/http/request.go

release 1.8.1

---

.rr.yaml
service/http/config.go
service/http/service.go

This PR adds RootCA support by the RR

Add RootCA support

---

service/http/config.go

Fixed error message in http/config.go

---

service/http/errors.go
service/http/errors_windows.go
service/http/handler.go
service/http/response.go
service/http/response_windows.go

- The issue with the broken pipe properly handled
- superfluous response.WriteHeader issue fixed

Broken pipe issue

---

static_pool.go

Since we are using pointer receiver for the StaticPool struct, there is no sense to use pointers to define mutexes.

Attempt to fix npe in the StaticPool mutex

---

osutil/isolate.go

Add checks to exec from user

---

plugins/app/app.go

- collects all app worker logs into a single channel

collect app logs into single channel

---

.github/workflows/ci-build.yml
.rr.yaml
Makefile
go.mod
go.sum
plugins/gzip/plugin.go
plugins/gzip/tests/configs/.rr-http-middlewareNotExist.yaml
plugins/gzip/tests/configs/.rr-http-withGzip.yaml
plugins/gzip/tests/plugin_test.go
plugins/gzip/tests/psr-worker.php
plugins/http/config.go
plugins/http/plugin.go
plugins/http/tests/configs/.rr-http.yaml

resolves #404 
1. Gzip middleware
2. Ordered middlewares in the HTTP plugin

Gzip plugin

---

.rr.yaml
service/metrics/config.go
service/metrics/config_test.go
service/metrics/rpc.go

Add objectives to the metrics summary

---

go.sum
plugins/checker/plugin.go
plugins/config/tests/plugin1.go
plugins/headers/plugin.go
plugins/http/plugin.go
plugins/http/tests/plugin1.go
plugins/http/tests/plugin_middleware.go
plugins/informer/tests/test_plugin.go
plugins/logger/plugin.go
plugins/logger/tests/plugin.go
plugins/metrics/plugin.go
plugins/metrics/tests/plugin1.go
plugins/reload/plugin.go
plugins/resetter/tests/test_plugin.go
plugins/rpc/tests/plugin1.go
plugins/server/plugin.go
plugins/server/tests/plugin_pipes.go
plugins/server/tests/plugin_sockets.go
plugins/server/tests/plugin_tcp.go
plugins/static/plugin.go

plugin/redis [reopen]

---

.rr.yaml
CHANGELOG.md

https://github.com/spiral/roadrunner/milestone/18?closed=1

1.9.2 release milestone

---

bin/rr
composer.json

Fixes: #492 
Added composer.json with reference to roadrunner-worker PHP codebase

Cross-reference PHP codebase

---

.dockerignore
.github/workflows/build.yaml
cmd/go.mod
cmd/go.sum

Wrong `Workers` method return type (for the `Informer`)
1. Update temporal plugin version (fix included)
~- [ ] Any required documentation changes (code and docs) are included in this PR.~

fix(activities): Update temporal plugin

---

CHANGELOG.md

RR-Core RC.3 release
1. Update version in CHANGELOG.md.

release(RC.3): RC.3 release

---

tests/broken.php
tests/delay.php
tests/echo.php
tests/head.php
tests/memleak.php
tests/pid.php
tests/plugins/server/socket.php
tests/plugins/server/tcp.php
tests/sleep.php
tests/slow-pid.php
tests/stop.php

Signed-off-by: Wolfy-J <wolfy-j@spiralscout.com>
In RoadRunner 2.0 all payloads are now carried using Payload DTO.
Update tests to reflect new worker API.

fix(php): PHP tests to use latest signatures

---

CHANGELOG.md
go.sum
pkg/pool/interface.go
pkg/pool/static_pool.go
pkg/pool/static_pool_test.go
pkg/pool/supervisor_pool.go
pkg/pool/supervisor_test.go
pkg/worker/interface.go
pkg/worker/sync_worker.go
tests/exec_ttl.php
tests/idle.php
tests/plugins/http/configs/.rr-http-supervised-pool.yaml
tests/plugins/http/http_plugin_test.go
tests/sleep.php

closes #558 
closes #560 
- Update supervisor Exec function.
- Make `execWithTTL` private.
- Mark worker as Invalid instead of immediately killing.
- Update tests.

🐛 fix(supervisor): supervisor behavior update

---

.rr.yaml
plugins/server/plugin.go

closes #573 
🐛 Fix: incorrect PHP command validation

🐛 fix(bug): remove php command path validation

---

.golangci.yml
plugins/http/config/http.go
plugins/http/config/ssl.go
plugins/http/plugin.go

closes #587 
- 🐛 Make a root_ca optional to run the SSL server.

fix(http): make a root_ca optional to start the SSL server

---

CHANGELOG.md
plugins/http/config/http.go
plugins/http/plugin.go

closes #583 
👷 Correct internal HTTP redirect code when redirected from HTTP to SSL
~- [ ] All added/changed functionality is tested.~

👷 correct(http):  http internal redirect code changed from 307 to 308

---

.github/workflows/linux.yml
Makefile
plugins/http/handler.go
plugins/http/plugin.go
tests/plugins/gzip/configs/.rr-http-middlewareNotExist.yaml
tests/plugins/gzip/configs/.rr-http-withGzip.yaml
tests/plugins/http/configs/.rr-big-req-size.yaml
tests/plugins/http/configs/.rr-broken-pipes.yaml
tests/plugins/http/configs/.rr-env.yaml
tests/plugins/http/configs/.rr-fcgi-reqUri.yaml
tests/plugins/http/configs/.rr-fcgi.yaml
tests/plugins/http/configs/.rr-h2c.yaml
tests/plugins/http/configs/.rr-http-supervised-pool.yaml
tests/plugins/http/configs/.rr-http.yaml
tests/plugins/http/configs/.rr-resetter.yaml
tests/plugins/http/configs/.rr-ssl-push.yaml
tests/plugins/http/configs/.rr-ssl-redirect.yaml
tests/plugins/http/http_plugin_test.go
tests/plugins/logger/configs/.rr-no-logger2.yaml
tests/plugins/reload/configs/.rr-reload-2.yaml
tests/plugins/reload/configs/.rr-reload-3.yaml
tests/plugins/reload/configs/.rr-reload-4.yaml
tests/plugins/reload/configs/.rr-reload.yaml
tests/plugins/static/configs/.rr-http-static-disabled.yaml
tests/plugins/static/configs/.rr-http-static-files-disable.yaml
tests/plugins/static/configs/.rr-http-static-files.yaml
tests/plugins/status/configs/.rr-status-init.yaml
tests/plugins/status/plugin_test.go

closes #584 
- 👷 Rework `ServeHTTP` handler logic. Use `http.Error` instead of writing code directly to the response writer. Other small improvements.
~- [ ] Any required documentation changes (code and docs) are included in this PR.~

🐛 fix(http): issue with strange messages in the http body when max request size reached

---

CHANGELOG.md
Makefile

closes #668 
- Remove old Makefile targets, which are irrelevant now.
~- [x] All added/changed functionality is tested.~

fix(makefile): remove old targets

---

pkg/worker_handler/handler.go

close: #489 
- Push events asynchronously.

feat(metrics): make `workers_hanler` listener events async

---

.github/workflows/linux.yml
.github/workflows/windows.yml
CHANGELOG.md
Makefile
plugins/websockets/config.go
plugins/websockets/connection/connection.go
plugins/websockets/executor/executor.go
plugins/websockets/origin.go
plugins/websockets/origin_test.go
plugins/websockets/plugin.go
plugins/websockets/pool/workers_pool.go
plugins/websockets/wildcard.go
tests/plugins/websockets/websocket_plugin_test.go
tests/worker-origin.php

closes: #727 
- Add wildcard and direct checks for the request origin.
- Update response payloads.
- Switch from the binary messages to text.

bug(websockets): not properly checked request origin

---

plugins/jobs/drivers/sqs/consumer.go
plugins/jobs/pipeline/pipeline.go
tests/plugins/jobs/jobs_sqs_test.go

- Fix SQS map parser.
- Fix SQS drivers map handler inside the `Declare` RPC call. 

fix(jobs, sqs): fix sqs `attributes` and `tags` parser

---

CHANGELOG.md
plugins/http/attributes/attributes.go

closes: #789
- Use existing context for the `http.Request` if `PsrContextKey` exists.

bug(attributes): make `attributes.Init` idempotent

---

.github/workflows/linux.yml
bors.toml
go.mod
go.sum
pool/supervisor_test.go
priority_queue/binary_heap_test.go
worker_watcher/worker_watcher.go

- Tech debt
- Cleanup tests. Especially `Supervisor_DebugMode` test.
Reduce memory usage under the high load (>`100k` RPS) by 7-10% approx
New:
Old:

refactoring(test,code): cleanup tests, code

---

events/docs/events.md
events/events.go
events/events_test.go
events/types.go
events/wildcard_test.go
pool/static_pool.go
transport/pipe/pipe_factory_test.go

closes: #496 
- Add docs (docs/events.md)
- Update tests

refactoring(eventsbus): add docs, udpate tests

---

utils/network.go

- TCP Retransmissions if a write operation was first
- Set `TCP_DEFER_ACCEPT` to false to false by default

upd(listener): set `TCP_DEFER_ACCEPT` to false

---

CHANGELOG.md

upd(changelog): v2.5.1 changelog update

---

worker_watcher/container/channel/vec.go

- closes: #853 
- Cover all cases with non-blocking send.

fix(vector): non-blocking send in all cases

---

CHANGELOG.md
go.mod
go.sum
pool/static_pool.go

- Zombie process on every request in the `pool.debug` mode.
- Read process exit status to prevent zombie processes

bug(pool, debug mode): zombie processes when the `pool.debug` mode is used
