spiral/roadrunner

go.mod
update vgo dependency `github.com/spiral/goridge` to recently release v2.1.2, because v1.4.1 is too old, when execute `make` command to build the application, there are some error
service/rpc/service.go:70:25: undefined: goridge.NewCodec
service/rpc/service.go:121:32: undefined: goridge.NewClientCodec
./worker.go:50:5: undefined: goridge.Relay
make: *** [all] Error 2
=> update vgo dependency

composer.json, src/PSR7Client.php
With this Pull Request `PSR7Client` now accepts `ServerRequestFactoryInterface`, `StreamFactoryInterface` and `UploadedFileFactoryInterface` instances in its constructor to customize the PSR-7 implementation returned by `PSR7Client::acceptRequest()`. The goal of this change is to simplify the integration of roadrunner with several other PSR-7 frameworks, such as Slim.
All three dependencies are optional. When they are not explicitly passed `http-interop/http-factory-diactoros` is used by default.
Everything should be backwards-compatible except for one tiny detail: calling `withProtocolVersion($ctx['protocol'])` on a Diactoros `ServerRequest` breaks several http tests. I haven't figured out what's the problem yet, for now this value is left hardcoded to `1.1`.
(FTR, the [initial …
=> [Feature] Decouple Diactoros from PSR7Client::acceptRequest() via PSR-17 HTTP factories

service/static/service.go
=> Fix typo in naming of dep in static service

src/PSR7Client.php
Resolves #60 
After investigation of Latavel behavior, I found that Laravel and Symfony working in some places with headers as _SERVER params with HTTP_ prefix. 
Some people even recommended using _SERVER to retrieve headers (https://stackoverflow.com/questions/541430/how-do-i-read-any-request-header-in-php).
This request writes all headers to $server param, so SF and Laravel can access it.
=> Fix headers in _SERVER (Laravel integration fix)

src/HttpClient.php, src/PSR7Client.php
Hi!
As partially discussed in #105 this is the first stage of removing PSR Deps and allowing to work directly with a raw request from RoadRunner and response.
This PR will allow creating more optimized Symfony and Laravel integrations.
=> Raw HTTP client (HttpClient), PSR7Client now depends on HttpClient

service/http/handler_test.go, service/http/request.go
=> Fix application/x-www-form-urlencoded parsing

qbuild/src/Builder.php
Built on macOS however windows binary `rr.exe` is generated.
Change order of condition. OS name `darwin` also has `win` in it. `win` should be checked after `darwin`.
=> Fix build issue on macOS

cmd/rr/.rr.yaml, service/http/config.go, service/http/config_test.go, service/http/handler.go, service/http/handler_test.go, service/http/rpc_test.go, service/http/service_test.go, service/http/uploads_test.go, service/static/service_test.go
Added `MaxRequestSize` param, the previous one is marked as deprecated,
now they are merged until next major release
=> Rename MaxRequest config param

service/limit/service.go
I've noticed that limiting functionality doesn't work as expected - rr simply ignores limit settings. I found out that the reason is the wrong `limit.ID` value. I tried to cover this case with test,  but I couldn't find similar tests and couldn't write such test from scratch.
=> Correct limit service ID

bin/rr
1.If system is linux `tempnam` create empty file, but then created new file with `.tar.gz` extension (and not deleted after download)
2. Wrong path in init config command
=> fix wrong config path and not deleted empty files in bin/rr

.rr.yaml, .travis.yml, cmd/rr/main.go, service/health/config.go, service/health/config_test.go, service/health/service.go, service/health/service_test.go, state.go
This commit adds a health service which ensures that at least
one worker is active. Uses `isActive()` to determine if the
worker is ready. The health service runs on a seperate address.
Will return a HTTP 200 if health, HTTP 500 otherwise.
Fixes #192
Signed-off-by: Alex Price <aprice@atlassian.com>
=> adds a health service for determining the status of the workers

service/http/response.go, service/http/response_test.go
Neither PHP nor PSR-7 do not natively support HTTP trailers. Golang provides support and this PR enables trailers emulation. When PHP sends a "Trailer" header in response, supplying a comma separated list of headers they will be converted by RoadRunner to HTTP/2 trailers.
Resolves #209 
Any feedback is appreciated :bowing_man:
=> Provide support for HTTP/2 trailers

src/PSR7Client.php
Related issue: #226 
Additionally, makes the coverage of documented $_SERVER values more complete per [PHP $_SERVER documentation](https://www.php.net/manual/en/reserved.variables.server.php).
=> Adding REQUEST_METHOD to $_SERVER

.dockerignore, .github/workflows/ci-build.yml, CHANGELOG.md, Dockerfile, README.md
This PR closes #218
Added / changed:
- `.dockerignore` excludes unimportant files for building (docker context)
- `ci-build.yml` imcludes step for image building testing
- `Dockerfile` contains instructions for image building
Required steps after PR merging:
1. @spiralscout must register account on [hub.docker.com](https://hub.docker.com/)
1. [Create repository](https://hub.docker.com/repository/create) on docker.hub and setup:
1. Profit!
=> RR binary in Docker

error_buffer.go
Between lines 93-95 timer(`eb.wait`) can emit event and its `select` case will cause deadlock, because will can't(`select` wil be blocked) be able to read event from channel `eb.update`
example: https://play.golang.org/p/KuLEm4qnwSn
=> BUGFIX: deadlock on timer update in error buffer

build.sh
Please, make sure, that musl-gcc is installed
Instead, use build type commented in build.sh
Ubuntu: `sudo apt-get install musl-tools`
ArchLinux: (this is community-driven distribution) `yay -S musl`
Verified successfully on latest musl-1.2.0 with Alpine Linux
Resolves #258
=> Update build.sh, support musl target

.github/workflows/ci-build.yml, go.mod, go.sum, pipe_factory_test.go, service/headers/service_test.go, service/http/fcgi_test.go, service/http/h2c_test.go, service/http/rpc_test.go, service/http/service_test.go, service/http/ssl_test.go, service/limit/service_test.go, service/reload/config_test.go, service/reload/watcher_test.go, service/rpc/config_test.go, service/static/service_test.go, socket_factory_test.go, static_pool_test.go, util/network.go, util/network_windows.go, util/network_windows_test.go, worker_test.go
Fixes #220 
0. Add reuse, defer and fast-accept to tcp4 net.Listener
1. Add new target - macOS-latest for tests
2. Add new golang version go 1.14, remove go 1.12
3. Update various tests (timeouts, defers, goroutines order)
4. Add new tests for File Watcher (directory copy)
=> Address already in use error

Dockerfile
👋 I just want to propose this update, so I'm creating this as a draft PR so that it's even easier to +1 or -1.
Since the Label Schema convention [has become deprecated in favor of the Open Containers Initiative spec](http://label-schema.org/rc1/#background), this updates all of the previous Label Schema keys to [the OCI equivalent](https://github.com/opencontainers/image-spec/blob/master/annotations.md#back-compatibility-with-label-schema).
If you're concerned with removing the current labels and would to transition to the OCI spec after some time, I can update this to simply add the OCI labels as well. There is no harm in having both.
=> Update Dockerfile labels in favor of OCI spec

.github/workflows/ci-build.yml, CHANGELOG.md, bors.toml, build.sh, composer.json, src/HttpClient.php, src/PSR7Client.php, src/Worker.php
=> release 1.8.0

service/http/service.go
Fix HSTS header publish by default and can't overwrite from PHP.
— Serve an HSTS header on the base domain for HTTPS requests:
—— The `max-age` must be at least _31536000_ seconds (1 year).
—— The `includeSubDomains` directive must be specified.
—— The `preload` directive must be specified.
Reference: https://hstspreload.org
=> Fix HSTS header

go.mod, go.sum, plugins/http/tests/http_test.go, pool.go, static_pool.go, static_pool_test.go, supervisor_pool.go, sync_worker.go, sync_worker_test.go, worker_watcher.go
This event indicates that RR can't get workers from the stack during the allowed allocated timeout.
resolves #401
=> Add new pool event: EventNoFreeWorkers 

CHANGELOG.md, cmd/rr/cmd/root.go
[Cobra](https://github.com/spf13/cobra) help about `Version` struct field: <https://github.com/spf13/cobra#version-flag>
Closes #434
> p.s. Less code is better. Ever.
=> Add `rr --version` flag

plugins/logger/plugin.go, plugins/server/plugin.go
This PR fixes incorrect usage of the `server.NewWorkerPool` listeners function parameter.
`listeners` were not passed to the underline worker's pool.
=> [RR2] Bugfix/missed pool events

.rr.yaml, pkg/pool/config.go, pkg/pool/static_pool.go, plugins/http/config.go, plugins/http/handler.go, plugins/http/plugin.go, plugins/kv/boltdb/config.go, plugins/logger/config.go, plugins/redis/config.go, plugins/server/config.go, plugins/server/plugin.go, tests/plugins/config/plugin1.go
Viper doesn't support `yaml` structure tags, it uses `mapstructure`, ref: https://github.com/spf13/viper/issues/385#issuecomment-337264721
Package: https://github.com/mitchellh/mapstructure
This PR replaces all `yaml` tags with `mapstructure`
=> fix(yaml): Use mapstructure structure tags instead of yaml

pkg/pipe/pipe_factory_spawn_test.go, plugins/http/plugin.go, plugins/logger/plugin.go, plugins/server/plugin.go, tests/plugins/http/response_test.go
This PR fixes the Incorrectly set environment variables in the `server` plugin.
1. `const RR_RPC = "RR_RPC"` (value was empty)
2. `RR_HTTP` moved to the HTTP plugin
=> bug(server): Incorrectly set environment variables

Makefile, cmd/cli/workers.go, plugins/http/plugin.go, tests/plugins/http/configs/.rr-resetter.yaml, tests/plugins/http/http_plugin_test.go, tests/plugins/static/static_plugin_test.go
Better debug log messages for the http handler
issue #480
Update `log.Debug` message structure to include all needed information. Debug messages from the log will be in the form of:
`{"remote": "127.0.0.1", "ts": "3.273883ms", "resp.status": 201, "method": "GET", "uri": "http://localhost:10084/?hello=world"}`
=> refactor(http): Uniform debug message from the http hanlder

.github/workflows/build.yml, .rr.yaml, Makefile, plugins/http/config/http.go, plugins/http/config/ssl.go, plugins/http/config/ssl_config_test.go, plugins/http/plugin.go, tests/plugins/http/configs/.rr-fcgi-reqUri.yaml, tests/plugins/http/configs/.rr-fcgi.yaml, tests/plugins/http/configs/.rr-init.yaml, tests/plugins/http/configs/.rr-ssl-push.yaml, tests/plugins/http/configs/.rr-ssl-redirect.yaml, tests/plugins/http/configs/.rr-ssl.yaml, tests/plugins/http/http_plugin_test.go, tests/plugins/rpc/config_test.go, utils/network.go, utils/network_windows.go
fixes #412
fixes #422 
config:
1. `http.ssl` part, change `port -> address`. Address can be in form of: `:<port>` or `<host>:<port>`
2. Listener updated to handle parsing  all range of the addresses
3. Add tests for the new SSL config
4. Update `CreateListener` previous tests
From the user perspective now the RR2-SSL server is capable to listen addresses like `[tcp://]:6001, unix://file.sock`. 
New config sample:
```yaml
http:
address: 127.0.0.1:44933
#...
pool:
ssl:
address: :8892  #<-----------------------------NEW
redirect: false
cert: fixtures/server.crt
key: fixtures/server.key
rootCa: root.crt
```
=> feat(https): Allow https to listen on unix sockets

plugins/server/plugin.go
issue #511 
1. Remove command arguments check.
2. Leave the check of command args number. The minimum command should contain 2 args: `<executable> <script>` separated by space.
=> fix(server): remove command limitaion

cmd/cli/reset.go, cmd/cli/root.go, cmd/cli/workers.go
1. Broken `workers -i` command output
2. Race in the RPC call in the `reset` command
3. `-d` flag is broken
1. Broken `workers -i` command output
2. Race in the RPC call in the `reset` command
3. Add debug server goroutine (`-d` flag)
~- [ ] Any required documentation changes (code and docs) are included in this PR.~
=> bug(screen,race): fix race and workers stdout to screen

.github/workflows/codeql-analysis.yml, .rr.yaml, bors.toml, pkg/events/worker_events.go, pkg/pool/static_pool_test.go, pkg/pool/supervisor_test.go, pkg/states/worker_states.go, pkg/transport/pipe/pipe_factory_spawn_test.go, pkg/transport/pipe/pipe_factory_test.go, pkg/transport/socket/socket_factory_spawn_test.go, pkg/transport/socket/socket_factory_test.go, pkg/worker/sync_worker.go, pkg/worker/worker.go, plugins/informer/rpc.go, plugins/server/plugin.go, tests/composer.json, tests/plugins/http/http_plugin_test.go, tests/plugins/reload/reload_plugin_test.go
1. Leaking workers on `Reset` doesn't free resources holding a pointer to the stderr buffer.
2. Create a new `EventWorkerStderr` event which would be responsible for handling all `stderr` events and send them to the listener.
1. New event in the `pkg/events`
2. Remove all buffers, pools, pipes, mutexes from the `Worker`. Only `4.5MB` inuse-space objects for all worker (golang) lifetime.
3. Stderr events sending only via listeners. No dangling pointers after workers destroyed which prevent GC to free up resources.
4. Update `bors.toml` according to the new actions.
~- [ …
=> bug(leak): workers memory leak

.dockerignore, .github/dependabot.yml, .github/workflows/codeql-analysis.yml, .rr.yaml, cmd/go.mod, cmd/go.sum
Release branch
1. Update `roadrunner-core` to the version `beta.25`.
~- [x] Any required documentation changes (code and docs) are included in this PR.~
~- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.~
=> Release 25

composer.json
> Please Note: This PR is blocked by the presence of a `spiral/roadrunner-cli` package on the pakagist and can only be accepted after it appears in the packagist's repository. 
> 
> See https://github.com/spiral/roadrunner-cli/issues/1
The metapackage serves to provide a convenient way to install a set of dependencies. In this case, package `spiral/roadrunner` replaces the installation of three dependencies:
- `spiral/roadrunner-worker`
- `spiral/roadrunner-cli`
- `spiral/roadrunner-http`
- Added support for roadrunner cli tool (installer) package.
- Previously, it was located in the repository `spiral/roadrunner-worker`: https://github.com/spiral/roadrunner-worker/pull/9.
- Added `spiral/roadrunner-http` dependency.
- Note: If the user does not need it, then he can use the installation …
=> feat(composer): Actualize composer.json dependencies

.github/ISSUE_TEMPLATE/feature_request.md, .rr.yaml, CHANGELOG.md, plugins/gzip/plugin.go, plugins/http/plugin.go, plugins/static/plugin.go, plugins/status/config.go, plugins/status/interface.go, plugins/status/plugin.go, plugins/status/rpc.go, tests/plugins/checker/configs/.rr-checker-init.yaml, tests/plugins/checker/plugin_test.go, tests/plugins/gzip/plugin_test.go, tests/plugins/http/http_plugin_test.go, tests/plugins/static/static_plugin_test.go
closes #557 
closes #556 
- Remove unneeded mutex from the `http.Workers` method.
- Rename `checker` plugin package to `status`, remove `/v1` endpoint prefix (#557) 
- Add static, headers, status, gzip plugins to the `main.go`.
- Update tests
=> fix(various): Small fixes before release

CHANGELOG.md, plugins/http/plugin.go, plugins/logger/interface.go, plugins/logger/std_log_adapter.go, tests/plugins/http/configs/.rr-h2c.yaml, tests/plugins/http/http_plugin_test.go
closes #585 
- 🧑‍🏭  Add the ability to print http/https/fcgi to the RR logger under the `ERROR` log level
- 🔴 Redirected errors are: accepting connections, unexpected behavior from handlers, and underlying FileSystem errors
=> 🆕 new(http plugin): HTTP/HTTPS/FCGI servers errors redirected to the RR logger under the Error log level

.github/workflows/linters.yml, .github/workflows/linux.yml, CHANGELOG.md, plugins/metrics/plugin.go, tests/plugins/metrics/.rr-test.yaml, tests/plugins/metrics/metrics_test.go
metrics configured through config file are currently not working
see #571
metrics from other plugins are no longer stored in `collectors` `sync.Map`
but instead they are direcly registered into `prometheus.Registry`
ensuring only `prometheus.Collector` is stored in `collectors`
=> fix(metrics): remove statsProvider from metrics collectors sync.Map

CHANGELOG.md, plugins/logger/plugin.go
- Fix issue with logger `channels`.
- Remove redundant logger implementation
- Cherry-pick to the stable branch
=> fix(logger): remove redundant logger interface implementation

.github/workflows/linux.yml, CHANGELOG.md, pkg/pool/static_pool.go, pkg/pool/supervisor_test.go
closes #661 
- Add the `execDebugWithTTL` method to the pool to handle cases when the user uses supervisor with `execTTL` in debug mode.
- Update CHANGELOG
- Add tests
- [x The reason for this PR is clearly provided (issue no. or explanation).
=> fix(bug): RR does not respect `debug` mode when `exec_ttl` is set

go.mod, go.sum, pkg/bst/bst.go, pkg/bst/interface.go, pkg/pubsub/interface.go, plugins/gzip/plugin.go, plugins/http/plugin.go, plugins/memory/plugin.go, plugins/redis/fanin.go, plugins/redis/plugin.go, plugins/websockets/executor/executor.go, plugins/websockets/plugin.go, plugins/websockets/pool/workers_pool.go
- Refactoring
- Redis plugin uses its own storage (Sets) to store information about connection without wasting a RR memory.
- Completely remove any storage from the Websockets plugin (only `Subscriber` interface).
- Add a new method to the `Subscriber` interface - `Connections` which returns a hashmap with connections IDs associated with the particular topic.
- Use `sync.Pool` everywhere in the `WorkerPool` to handle big allocations of the hashmaps and byte slices.
- RR2 by benchmarks uses only ~100-120MB of `inuse_space` RAM per 10k WebSocket connections and ~150MB when bombarding with a lot of `Publish` operations.
- Expected (local) throughput for the 1CPU per 10k for Redis broker is around 100k messages per second and ~500k-1M (depending on your system) for `memory` driver.
By …
=> feat(websockets): bug fixing and polishing

.github/workflows/codeql-analysis.yml, CHANGELOG.md, pkg/worker_handler/handler.go, plugins/http/metrics.go, plugins/http/plugin.go, plugins/metrics/plugin.go, tests/plugins/metrics/configs/.rr-http-metrics.yaml, tests/plugins/metrics/metrics_test.go
closes: #489 
- Expose workers' memory stats via custom exporter implementation.
- Expose request count/duration metrics.
- Tests
-----
Metrics:
=> feat(metrics): expose HTTP metrics

internal/protocol.go, pkg/pool/static_pool_test.go, pkg/transport/socket/socket_factory.go, pkg/worker/state.go, pkg/worker/sync_worker.go, pkg/worker_watcher/container/vec.go
- Reduce frames and buffers allocations
- Use reusable `sync.Pool` pool of objects for hot-paths.
- CPU time for allocations reduced from 29.2% to 23.8% (especially `runtime.newobject`)
- Memory usage for the constantly loaded workers reduced from 18MB to 14MB (for the same payload).
- CPU time in `ns` reduced from `268ns` to `206ns`
Benchmarks were performed on Ryzen 5950X with 64Gb of RAM and 980PRO `nvme` and may vary depending on the hardware (`5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux, XFS fs`)
=> feat(opt): `inuse_space` and `runtime.newobject` optimizations

CHANGELOG.md, plugins/kv/drivers/boltdb/config.go, plugins/kv/drivers/boltdb/driver.go, tests/plugins/kv/configs/.rr-kv-bolt-no-interval.yaml, tests/plugins/kv/configs/.rr-kv-bolt-perms.yaml, tests/plugins/kv/storage_plugin_test.go
closes: #719 
closes: #718 
closes: #717 
- Fix interval initialization
- Fix default user permissions for the boltdb file (`777 -> 0777`)
- Add timeout when trying to open the same boltdb file from different processes.
=> fix(boltdb): fix boltdb permissions, interval, config bugs

CHANGELOG.md, pkg/pool/static_pool.go, pkg/pool/supervisor_pool.go, pkg/pool/supervisor_test.go, pkg/worker/sync_worker.go, pkg/worker_watcher/container/interface.go, pkg/worker_watcher/container/vec.go, pkg/worker_watcher/worker_watcher.go, tests/plugins/http/configs/.rr-http-supervised-pool.yaml, tests/plugins/http/http_plugin_test.go, tests/psr-worker-slow.php
closes #737 
closes #734 
- Fix deadlock in the `worker_watcher`.
- Fix incorrect workers state handling for the `healthcheck` endpoint. Now workers not in the `Working` state automatically stop by the supervisor and state properly updated.
This is the simplified version of the bug:
```golang
package main
import (
"context"
"time"
)
func main() {
s := NewStr()
ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
s.put()
for i := 0; i < 1000; i++ {
go s.foo(ctx)
}
cancel()
s.put()
s.put()
s.put()
s.foo(context.Background())
}
type str struct {
v chan struct{}
}
func NewStr() *str {
return &str{v: make(chan struct{}, 5)}
}
func (s *str) put() {
s.v <- struct{}{}
}
func (s *str) foo(ctx context.Context) {
r := make(chan struct{}, 1)
go func() {
time.Sleep(time.Second * 5) …
```
=> fix(allocator): workers were not reallocating when `exec_ttl` was hit

CHANGELOG.md
- Next release cycle.
- ✏️ Rework `broadcast` plugin. Add architecture diagrams to the `doc` folder. [PR](https://github.com/spiral/roadrunner/pull/732)
- ✏️ Add `Clear` method to the KV plugin RPC. [PR](https://github.com/spiral/roadrunner/pull/736)
- 🐛 Fix: Bug with channel deadlock when `exec_ttl` was used and TTL limit reached [PR](https://github.com/spiral/roadrunner/pull/738)
- 🐛 Fix: Bug with healthcheck endpoint when workers were marked as invalid and stay is that state until next request [PR](https://github.com/spiral/roadrunner/pull/738)
- 🐛 Fix: Bugs with `boltdb` storage: [Boom](https://github.com/spiral/roadrunner/issues/717), [Boom](https://github.com/spiral/roadrunner/issues/718), [Boom](https://github.com/spiral/roadrunner/issues/719)
- 🐛 Fix: Bug with incorrect redis …
=> feat(release): `v2.3.1` release

CHANGELOG.md, plugins/amqp/amqpjobs/item.go
- ref: https://github.com/spiral/jobs/issues/49
- Check all possible (for the amqp.Table) integer types.
- Add types check for the `RRDelay` and `RRPriority` to accept any of the `int`, `int16`, `int32`, or `int64`.
=> fix(amqp): type casting for the amqp headers

plugins/logger/zap_adapter.go, tests/plugins/logger/logger_test.go, tests/plugins/logger/plugin.go
When logging in a plugin it would be useful to take advantage of the underlying Zap library, in this case being able to create fields that define the key and the value to go to output or to even use object marshalling to apply multiple keys/interfaces to the output.
At current if a [Zap field object](https://pkg.go.dev/go.uber.org/zap#Object) is passed as an argument, you must provide a key with it to then be processed as an interface otherwise an error is thrown that an uneven number of arguments have been provided.
With this you can now do something like:
```go
import (
"go.uber.org/zap"
)
field := zap.String("error", "Example field error")
log.Error("error", field)
```
and get an output like:
```json
{"message":"error", "error": "Example field error"}
```
Equally the following code …
=> feat(logger): Zap fields can be used as arguments to logger

.vscode/settings.json, CHANGELOG.md, plugins/memory/memoryjobs/consumer.go, tests/plugins/jobs/jobs_memory_test.go
- Consume option for the in-memory plugin was a no-op. A user had to resume pipe manually.
- Made the `in-memory` driver behavior like all other jobs drivers.
=> fix(jobs, memory): start `jobs` `in-memory` driver automatically if the user consumes it

CHANGELOG.md, go.mod, go.sum, internal/protocol.go, tests/pipes_test_script.sh, tests/script.sh, tests/socket_test_script.sh, transport/pipe/pipe_factory.go, transport/pipe/pipe_factory_test.go, transport/socket/socket_factory.go, transport/socket/socket_factory_test.go
closes: #822 
- ✏️ Remove requirement to share the same PID for the worker and root process. 
According to the fork (and to be precise, `fork-exec` in go) man pages documentation, 
```text
The child inherits copies of the parent's set of open file descriptors.  
Each file descriptor in the child refers to the same open file description (see open(2)) as the corresponding file descriptor in the parent. 
This means that the two file descriptors share open file status flags, file offset, and signal-driven I/O attributes (see the description of F_SETOWN and F_SETSIG in fcntl(2)).
```
- ✏️ Server plugin can accept scripts (sh, bash, etc) in it's `command` configuration key:
```yaml
server:
command: "./script.sh OR sh script.sh" <--- UPDATED
relay: "pipes"
relay_timeout: "20s"
```
The script …
=> feat(pipes,sockets): allow running scripts in the server's command

.github/workflows/linters.yml, worker_watcher/worker_watcher.go
- Unused context in the worker watcher's `Destroy` method.
- Kill everything after `<-ctx.Done`.
- Update golangci-lint to `v1.43`.
=> feat(worker_watcher): make a `Destroy` context useful

worker_watcher/container/channel/vec.go, worker_watcher/worker_watcher.go
- ? https://github.com/spiral/roadrunner-plugins/issues/109
- non blocking channel send
- In some very rare cases, when several workers get TTL-ed, it may lead to the situation, where the first reallocated worker might be pushed into the channel right after we search for the TTL-ed worker in the channel. This is only possible when the channel is full of TTL-ed workers.
=> fix(vector): deadlock on the channel send
